### ISSUE TITLE
add outside library

### ISSUE THREAD

**Issue by MarcRohrer** [ocicl/ocicl#10]
Hi Anthony,

I want to try cl-collider. I copied it to the systems directory, but sbcl cannot find it.
How can I add it?

best wishes 

Marc

**Comment by MarcRohrer** [comment]
all examples are always using quicklisp and I currently could not get sbcl to load anything with plain asdf :-(

**Comment by atgreen** [comment]
You would just use regular asdf mechanisms to load your code.   For
instance...
(setf asdf:*central-registry* #p"/path/to/cl-collider-directory")
and then (asdf:load-system :cl-collider).

Or you could create a local-systems directory and copy all of your local
systems there and run..
(asdf:initialize-source-registry '(:source-registry
:ignore-inherited-configuration (:tree #P"/path/to/my/local/systems/")))

ASDF will search under /path/to/my/local/systems/ for cl-collider.asd.

I don't think there's any point in having an ocicl-specific local-project
directory because you can do the same thing with asdf, as above.  But
perhaps I can add this hint to the README.

AG

**Comment by MarcRohrer** [comment]
Hi Anthony,

Hints are always welcome :-)
I will try that asap.
I've been messing around with asdf for quite a while and could not get it to 
load anything up to now. We'll see...
Thanx!

Marc

**Comment by atgreen** [comment]
I've added a note on this to the README under Tips and Troubleshooting.  Let me know how it works out.

**Comment by MarcRohrer** [comment]
Hi Anthony,

sorry for not responding. I currently don't have time to venture into cl at all.
But I am still heavily interested!

With the loading issue. This seems to have been primarily triggered by me not understanding some basic concepts, espacially that packages are simply "namespaces".

Thank you very much for your help!

Marc
