### ISSUE TITLE
Handling version updates

### ISSUE THREAD

**Issue by rudolfochrist** [ocicl/ocicl#22]
What is the process for version updates of a specific system, e.g. when I bump the version from `cl-change-case-0.2.0` to `cl-change-case-0.2.1`. Do I need to open a new issue to add the 0.2.1 version? 

Would it be a valuable addition to extend the `ocicl` executable to publish new artifacts? I imagine something like
```shell
ocicl publish 
# or
ocicl publish --version 0.2.1
```
inside the system source directory. 

Thank you.
-Sebastian

**Comment by atgreen** [comment]
These are good questions.  I don't like the idea of publishing from ocicl itself, because .. how are people authorized to do this?  The vast majority of systems don't use version tags, so the git repos are periodically scanned for updates and the commit hash in the README.org is updated.  This triggers a build.
I don't have a good solution for versioned systems yet.  One idea is to scan the git repos for updates and update them accordingly.

In the meantime, just file a ticket against the system's ocicl project
